### ISSUE TITLE
Fix Speakers Section Not Properly Centering on Smaller Screens

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/sparkhacks-2023#163] opened 2023-02-26 03:58 UTC
The pictures from this section should wrap around nicely and stay centered which they are currently not doing.
![image](https://user-images.githubusercontent.com/42191425/221391565-36a40075-7bdf-4e07-aae3-44bec9e90fb4.png)
DoD:
- The images stay centered when wrapping

**Comment by Abhishek7Tech** [comment] 2023-03-02 07:50
Hi @ChristianBingman the issue is - a 3 column grid is used for medium screen sizes. 

Solution: I am using flex to center the images. This is the progress I have made until now. Check the video below and share feedback please.

https://user-images.githubusercontent.com/93655183/222364567-5db0e9d2-d7fc-424e-bc7b-313c81507552.mp4

**Comment by ChristianBingman** [comment] 2023-03-03 04:16
Looks good, please upload your code.

**Comment by Abhishek7Tech** [comment] 2023-03-03 05:01
@ChristianBingman  Please Check, PR for fixed speaker section to center for medium screens #185

**Comment by Abhishek7Tech** [comment] 2023-03-11 16:25
@ChristianBingman Please Check, PR!

**Comment by ChristianBingman** [comment] 2023-03-13 00:45
I left a note, the package-lock is still there.

**Comment by Abhishek7Tech** [comment] 2023-03-13 05:59
@ChristianBingman Done!

**Comment by Abhishek7Tech** [comment] 2023-03-13 15:33
@ChristianBingman Done!

**Comment by Abhishek7Tech** [comment] 2023-03-15 12:10
@ChristianBingman close this issue please!

**Closed** 2023-03-15 15:23 UTC
Labels: bug, good first issue
